### ISSUE TITLE
Buttons for pattern library

### ISSUE THREAD

**Issue by jiannanolan** [EasyGiftRegistry/easy-gift-registry#14]
Create buttons for pattern library. 
Commit to pattern library.

**Comment by AspirationYC** [comment]
Hey @jiannanolan, @MichaelaRob

I finished the buttons. Here are what they look like:
 `btn `
<img width="135" alt="basic-btn" src="https://user-images.githubusercontent.com/31771017/73110839-d8887880-3ed5-11ea-9569-11ace8b06d8b.png">
`btn:hover`
<img width="142" alt="basic-btn-hover" src="https://user-images.githubusercontent.com/31771017/73110857-f35aed00-3ed5-11ea-9331-3d054695b76b.png">
`btn-ghost`
<img width="142" alt="ghost-btn" src="https://user-images.githubusercontent.com/31771017/73110884-0ec5f800-3ed6-11ea-8c5d-5a1cc37a45d7.png">
`btn-ghost:hover`
<img width="143" alt="ghost-btn-hover" src="https://user-images.githubusercontent.com/31771017/73110907-28ffd600-3ed6-11ea-8906-89daf09c4f9a.png">
`btn-light`
<img width="145" alt="light-btn" src="https://user-images.githubusercontent.com/31771017/73110932-3f0d9680-3ed6-11ea-9404-5373935151bb.png">
`btn-light:hover`
<img width="142" alt="light-btn-hover" src="https://user-images.githubusercontent.com/31771017/73110946-4cc31c00-3ed6-11ea-80ec-b0a0557c7839.png">

If you want me to change some colours, please let me know!

**Comment by jiannanolan** [comment]
Buttons were completed and added to master
