### ISSUE TITLE
Grid not working

### ISSUE THREAD

**Issue by jiannanolan** [EasyGiftRegistry/easy-gift-registry#68]
@thomasjbradley

Hi thomas, 

I'm having some issues with the grid that I can not figure out. On the registration, search page and profile page the grid doesn't seem to be filling up the entire width and therefore the 4th column is jumping down to the next row instead of staying on the same line. When inspecting this issue it seems to work when the line-length is disabled, but therefore it messes the text up.

I also was wondering if there was a way of hiding additional cards so that the grid works better as all themes do not perfectly multiply by 4, 3, 2.... For more context, I have the entire section pulling md product files from a theme (ie. birthday, . So there not individually added, so I don't know how to just cut off the bottom row. 

Thanks!

**Comment by thomasjbradley** [comment]
*For the grid:*

I don’t think you need this unit, because you end up having a unit directly inside a unit.
https://github.com/EasyGiftRegistry/easy-gift-registry/blob/master/_patterns/sections/profile-theme-section.html#L2

**Comment by thomasjbradley** [comment]
*For the number of cards:*

Really, I think the absolute easiest solution is to just make sure they’re all divisible. Make sure there are always 12 cards and the division will work out.

**Comment by jiannanolan** [comment]
@thomasjbradley 
Would adding to the amount of cards mess up the scrolling calculations we established on the homepage through the section.css? I was just worried that by adding to the themes that this would break this function.

**Comment by jiannanolan** [comment]
Issue has been resolved!
